name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.6
        with:
          go_version_file: go.mod
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test ./... -short -v -coverprofile=./coverage.txt -race -vet=off
      - name: Upload coverage data
        uses: codecov/codecov-action@v4.4.1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: coverage.txt
          path: coverage.txt
